version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: cd app
      - run: ls
      - run: echo "this is the build job"

  test:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout
      - run: php app/composer.phar install
      - run: echo "this is the test job"

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test