version: 2.1
executors:
  default:
    docker:
      - image: circleci/php:7.3-apache-node-browsers-legacy
    working_directory: /tmp/repo

# このプロジェクトで実行するジョブの定義
jobs:

  build:
    executor:
      name: default
    steps:
      - checkout
      - run: composer install -n --prefer-dist --working-dir=./app
      - run: npm -v
      - run: npm install --prefix ./app
      - run: npm run production --prefix ./app
      - run: echo "this is the build job"
      - persist_to_workspace:
         root: /tmp/repo
         paths:
           - app/*
  test:
    executor:
      name: default
    steps:
      - attach_workspace: 
          at: /tmp/repo
      - run: ls
      - run:
          name: Test run
          command: |
            cd ./app
            php artisan test
  deploy:
    executor:
      name: default
    steps:
      - attach_workspace: 
          at: /tmp/repo
      - run: ls
      - run: echo "deploy job!"

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
    