version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: circleci/php:7.3-apache-node-browsers-legacy
    steps:
      - checkout
      - run: composer install -n --prefer-dist --working-dir=./app
      - run: npm -v
      - run: npm install --prefix ./app
      - run: npm run production --prefix ./app
      - run: echo "this is the build job"

  test:
    docker:
      - image: circleci/php:7.3-apache-node-browsers-legacy

    steps:
      - checkout
      - run: echo "this is the test job"

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test