version: 2.1
executors:
  default:
    docker:
      - image: circleci/php:7.3-apache-node-browsers-legacy
    working_directory: /tmp/workspace

# このプロジェクトで実行するジョブの定義
jobs:

  build:
    executor:
      name: default
    steps:
      - checkout
      - run: npm -v
      - run:
          working_directory: app
          command: composer install -n --prefer-dist
      - run:
          working_directory: app
          command: npm install
      - run: 
          working_directory: app
          command: npm run production
      - persist_to_workspace:
         root: /tmp/repo
         paths:
           - app/*

  test:
    executor:
      name: default
    steps:
      - attach_workspace: 
          at: /tmp/repo
      - run: ls
      - run:
          working_directory: app
          command: php artisan test

  deploy:
    executor:
      name: default
    steps:
      - attach_workspace: 
          at: /tmp/repo
      - run: 
          working_directory: app
          command: ls
      - run: echo "deploy job!"

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
    